# Data
### bikes.json
File downloaded from https://data.sfgov.org/api/views/w969-5mn4/rows.json containing SF Bike Parking slots
### loader.py
Python script used to create the seed script 
It will only work with the above mentioned url
### seed.sql
Seed sql script generated by loader.py
### DB
The backend database is Postgres.